### ISSUE TITLE
Version 0.1.27 gives error on startup

### ISSUE THREAD

**Issue by vadimnazaroff** [GuyKh/ims-custom-component#101]
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 18:15:35 (1 occurrences)
Last logged: 18:15:35

Error setting up entry IMS Weather for ims
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ims/__init__.py", line 57, in async_setup_entry
    unique_location = f"ims-{language}-{city['lid']}"
                                        ~~~~^^^^^^^
TypeError: 'int' object is not subscriptable

**Comment by GuyKh** [comment]
Try to remove and reinstall.

**Comment by aradzil** [comment]
I had the same problem after the upgrade.
Reinstall solved the issue.
Thanks.

**Comment by refaelOW** [comment]
But also after reinstalling if adding sensor in config the issue still exists, error on loading

**Comment by GuyKh** [comment]
Added version 0.1.28 to try to fix it - try it.

**Comment by refaelOW** [comment]
Great!!! Thanks
It works with 0.1.28
