### ISSUE TITLE
Version 0.1.28 still makes problems since version 0.1.27

### ISSUE THREAD

**Issue by refaelOW** [GuyKh/ims-custom-component#105]
Looks like it still has a problem with city field.

An existing IMS weather coordinator already exists for this location. Using that one instead

**Comment by refaelOW** [comment]
First install I get this config screen with a combobox to
Choose the city:

![image](https://github.com/user-attachments/assets/df5f13df-94c8-4599-b21f-4f461e014135)

After homeassistant reboot this is the configure screen, only numbers can be inputted to the city field, looks like Ariel city is not working properly, I think using a different city worked for me:

![image](https://github.com/user-attachments/assets/1149d557-53d6-4719-a516-8b44ac1c0789)

**Comment by GuyKh** [comment]
There's an issue with the reconfigure flow. But the functionality should work.

What's not working? And what are the logs say?

**Comment by refaelOW** [comment]
![image](https://github.com/user-attachments/assets/7ee577ef-c9b9-41e2-b4e0-946331b07e95)

![image](https://github.com/user-attachments/assets/ec7174fd-7bd9-4395-8fab-ae75ae7d3ad0)

This is all I found

**Comment by GuyKh** [comment]
Try the physical 'home-Assistant.log' file

**Comment by GuyKh** [comment]
Also, for me to reproduce, take a screenshot of what you're trying to add (configuration)

**Comment by refaelOW** [comment]
I found that there where ims entities left from previous installed ims add on, so I deleted them all and reinstalled the ims and for now it looks like it works.

I will let you know if it fails again.

Are you fixing the reconfigure screen soon?

Thanks

**Comment by refaelOW** [comment]
Now again it suddenly became unavailable and this is the error shown in the log:
![image](https://github.com/user-attachments/assets/72ed613b-6507-44f5-bd24-90c1adf9828d)

**Comment by GuyKh** [comment]
This is `timeout` - meaning, the component wasn't able to communicate with ims service.
Restart would reset the alert, but it has nothing to do with the code.

**Comment by GuyKh** [comment]
> Are you fixing the reconfigure screen soon?

Working on it

**Comment by nasser83** [comment]
hello @GuyKh,
installing for the first time, while installing got the "city name" drop down and upon completion got error "failed to setup"
opened configuration again it was empty and this time its asking for a city code instead of city name dropdown
choosing 44 (Nof Hagalil) failed, for testing i choose 21 (Raanana) and it worked
can you please check the issue?

**Comment by GuyKh** [comment]
@nasser83
please open a separate issue for this.

Also, from the logs, get the error message
