### ISSUE TITLE
Feature Requests: Rain on forecast and English weather description

### ISSUE THREAD

**Issue by yalmog99** [GuyKh/ims-custom-component#112]
Hi,
I would like to suggest 2 features:
1. Adding Rain data on forecast. It will allow to be able to know if tomorrow rain is expected.
2. Adding also English weather description and not only Hebrew. It will allow Alexa users to use this data on TTS since hebrew is not supported.

My goal is to be able to send Voice notification on Alexa every evening about tomorrow rain forecast and the weather description.

Is it possible ?

Thanks

**Comment by GuyKh** [comment]
As for (1) - check these two posts out:
https://community.home-assistant.io/t/daily-weather-forecast-notification/715411 (Blueprint you can import)
https://community.home-assistant.io/t/getting-tomorrows-forecast-at-a-specified-time-of-day/435914/3

As for (2) - please elaborate on where you see the weather description

**Comment by GuyKh** [comment]
As far as I can see, the `weather` entity state (and forecast state) is HomeAssistant predefined states (e.g. `partlycloudy`) - it's being translated automatically by HA

**Comment by yalmog99** [comment]
@GuyKh thanks.
1. I know how to make this automation. The problem is that the integration does not supply the rain information in the entity sensor.ims_forecast_day1. Am I wrong ? See the screet shot and data below for information available (no rain data).
2. in the same entity the value description is in Hebrew. See below

minimum_temperature: 
value: 20
unit: °C

maximum_temperature: 
value: 28
unit: °C

maximum_uvi: 
value: 7
unit: UV index

weather: 
value: מעונן חלקית
icon: mdi:weather-partly-cloudy

description: 
value: מעונן חלקית עד בהיר. תחול ירידה קלה בטמפרטורות בעיקר בהרים ובפנים הארץ.

date: 
value: 2024/10/10


![Screenshot 2024-10-09 131306](https://github.com/user-attachments/assets/b4727a17-5086-4ef7-a62f-54441998552d)

**Comment by GuyKh** [comment]
1. Note that here you use the `weather.get_forecast` action, rather than checking the `sensor.ims_forecast_day1`. This approach is much better IMO
2. As you can see - everything is in Hebrew - i.e. weather_condition etc. Are you sure that when configuring you selected `en`? 
![image](https://github.com/user-attachments/assets/d740ce19-8250-44b3-b4df-774dd84e2eda)

**Comment by yalmog99** [comment]
Thanks @GuyKh 
1. Using weather.get_forecast does not return rain information. see Screen Shot below.  I think the integration does not supply the forecast rain data information. Am I wrong ?
2. I changed it to "en" and it fix the English/Hebrew problem. Thanks.

![Screenshot 2024-10-10 083246](https://github.com/user-attachments/assets/ac238200-0247-426d-bdcf-0a71decd2c74)

**Comment by GuyKh** [comment]
I'm checking - 
First of all - you can use `condition == 'rainy'` (note that you get the datetime with UTC timezone - so consider that - I'm planning to [fix this soon](https://github.com/GuyKh/ims-custom-component/pull/113))


Next - looking at what returns from IMS data - they serve daily and hourly forecasts:
```
        "forecast_data": {
            "2024-10-10": {
                "country": {
                    "forecast_day": "2024-10-10",
                    "created": "2024-10-10 04:50:05",
                    "description": "Today: Partly cloudy to clear ,mainly in the mountains and inland areas a slight drop in temperatures.\n\nTonight: Partly cloudy."
                },
                "daily": {
                    "id": "105197882",
                    "lid": "2",
                    "forecast_date": "2024-10-10",
                    "weather_code": "1220",
                    "minimum_temperature": "22",
                    "maximum_temperature": "28",
                    "maximum_uvi": "7",
                    "created": "2024-10-07 15:06:19",
                    "u_v_i_factor": "1"
                },
                "hourly": {
                    "00:00": {
                        "lid": "2",
                        "day": "2024-10-10",
                        "hour": "00",
                        "weather_code": "1220",
                        "rain_chance": "0",
                        "wave_height": "0.5",
                        "forecast_time": "2024-10-10 00:00:00",
                        "temperature": "24",
                        "precise_temperature": "23.9",
                        "heat_stress_level": "1",
                        "heat_stress": "22.7",
                        "relative_humidity": "81",
                        "rain": null,
                        "wind_direction_id": "6",
                        "wind_speed": "2",
                        "wind_chill": "24",
                        "u_v_index": "0",
                        "u_v_i_max": null,
                        "created": "2024-10-06 19:56:25"
                    },
```

As you can see, the daily forecast doesn't contain daily precipitation.
This could be a feature requests to calculate, but for now, you can achieve it by yourself by summing all hourly precipitation units of tomorrow

**Comment by yalmog99** [comment]
@GuyKh - thanks.
The condition == 'rainy' is for now, I want the rain forcast of tomorrow (for Voice notification every night on tomorrow rain condition).
Can you suggest an automation that sum the all hourly precipitation units of tomorrow ?

**Comment by GuyKh** [comment]
As i noticed, when you get forcasts here: https://github.com/GuyKh/ims-custom-component/issues/112#issuecomment-2404067665
You can check when it's rainy.
