### ISSUE TITLE
Wind bearing is inverted

### ISSUE THREAD

**Issue by pshotts** [GuyKh/ims-custom-component#117]
The wind_bearing attribute of the IMS weather entity is exactly the inverse (180° different) from that reported by IMS.

Wind direction in all weather sites (and other HA integrations) is the direction from which the wind is coming. (A traditional weathervane would always point in that direction.)

**Comment by pshotts** [comment]
I have to add that, apart from this issue, your integration is extremely valuable to me.
Thank you for your hard work creating and maintaining it!

**Comment by GuyKh** [comment]
@pshotts - Thanks for pointing it out
This is [IMS mapping](https://ims.gov.il/en/wind_directions) - ID to direction
This is what I have in [my code](https://github.com/GuyKh/ims-custom-component/blob/main/custom_components/ims/const.py#L141) - ID to degrees.

It indeed seems inverted.
I'll fix that

**Comment by GuyKh** [comment]
Fixed in 0.1.31.

Also - if you want a deeper "status" component - check out https://github.com/GuyKh/ims-envista-custom-component
It's also from IMS, only you can select specific weather stations (and more data).
Also - note that you need to contact them for a token which is required

**Comment by pshotts** [comment]
Wow!
Thank you for that amazing quick fix!
I will certainly be installing your envista version because that gives me access to Zikhron Yaaqov data, and that station is about 200 metres from my home!
Just got to get my token...
