### ISSUE TITLE
Error while setting up ims platform for sensor

### ISSUE THREAD

**Issue by bensil1** [GuyKh/ims-custom-component#12]
Logger: homeassistant.components.sensor
Source: custom_components/ims/sensor.py:72
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:21:37 PM (1 occurrences)
Last logged: 10:21:37 PM

Error while setting up ims platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ims/sensor.py", line 72, in async_setup_platform
    config_entry[IMS_PLATFORM] = [IMS_PLATFORMS[0]]
NameError: name 'config_entry' is not defined

I don't know if it makes a difference, but the sensors are in a separate file and not in a configuration file

**Comment by baget** [comment]
got the same issue, not sure why...

**Comment by baget** [comment]
I found the solution; you need to use the UI and not yaml to add this integration.

**Comment by vadimnazaroff** [comment]
> I found the solution; you need to use the UI and not yaml to add this integration.

What are the exact steps you followed to resolve?

**Comment by t0mer** [comment]
You need to remove it from the configuration file and add it using the UI
