### ISSUE TITLE
Hourly temperature issue

### ISSUE THREAD

**Issue by ofirmanor** [GuyKh/ims-custom-component#121]
Hi, I have installed the IMS component (works great) and added some visualization for daily and hourly forecast (using latest HA and IMS). Thanks for sharing it!

I am a bit annoyed that the hourly stuff looks weird in visualization. Looks like each hour has a big range of temperatures (look at 22:00 at 23:00), while I thought they all should look like the one I circled (right side):
![image](https://github.com/user-attachments/assets/d572640f-9f47-4d6f-87eb-5784f8fde365)

Anyway, looking at the entity hourly tab, it seems HA have a big range of temperatures per hour. Also, looking closely, it seems to me it picks / derives the hourly minimum from the daily minimum (see how the hourly minimum is constant across all hours of each day).
Is there a way to tell HA that the min and max temperature of each hour are just the reading of that hour? It would make the visualization beautiful.
Not sure if the issue is on your side or HA side
![image](https://github.com/user-attachments/assets/192a3bd5-9f6b-472b-b7b9-b4f3c86b1f63)

**Comment by GuyKh** [comment]
Your analysis was spot on.
Indeed ([here](https://github.com/GuyKh/ims-custom-component/blob/main/custom_components/ims/weather.py#L278)) - the min_temp is taken from the daily minimum.

As IMS doesn't provide hourly minimum or range ([for example](https://ims.gov.il/he/city_portal/2)):
```json
{
    "hourly": {
         // ....
        "05:00": {
            "lid": "2",
            "day": "2024-11-07",
            "hour": "05",
            "weather_code": "1250",
            "rain_chance": "0",
            "wave_height": "0.7",
            "forecast_time": "2024-11-07 05:00:00",
            "temperature": "19",
            "precise_temperature": "19.0",
            "heat_stress_level": "0",
            "heat_stress": "17.3",
            "relative_humidity": "71",
            "rain": null,
            "wind_direction_id": "3",
            "wind_speed": "5",
            "wind_chill": "19",
            "u_v_index": "0",
            "u_v_i_max": null,
            "created": "2024-11-02 23:11:25"
        }
    }
```

I tend to agree and remove the min_temp from forecasts

**Comment by GuyKh** [comment]
Solved in 0.1.32

**Comment by ofirmanor** [comment]
Thanks @GuyKh !
![image](https://github.com/user-attachments/assets/91be8f4c-fc1a-49c3-9dc4-60fb9d696148)

**Comment by yalmog99** [comment]
@ofirmanor, can you share the code for the nice graphics you mentioned in your post ?
Which Card do you use ?

**Comment by ofirmanor** [comment]
Sure @yalmog99 , I am still playing with it (see the mix of Hebrew and English...), but for now these are my two cards, both with clock-weather-card from HACS.
![image](https://github.com/user-attachments/assets/de64b47d-d0b4-4614-8ef5-d73278df3a40)

**Daily forecast** ( card-mod to center to title text)
```
type: custom:clock-weather-card
entity: weather.ims_weather
forecast_rows: 6
title: תחזית יומית
weather_icon_type: fill
show_humidity: false
time_pattern: H:mm
date_pattern: cccc, LLL M
card_mod:
  style: |
    ha-card  {
      text-align: center;  
    }
```
**Hourly forecast** (using card-mod also to remove the redundant rightmost temp display)
```
type: custom:clock-weather-card
entity: weather.ims_weather
title: תחזית שעתית
hourly_forecast: true
forecast_rows: 12
locale: EN-IL
hide_today_section: true
card_mod:
  style: |
    ha-card  {
      text-align: center;  
    }
    clock-weather-card-forecast-row forecast-text:last-of-type {
      display: none;
    }
    clock-weather-card-forecast-row forecast-temperature-bar {
      grid-column: 4/6;
    }
```

**Comment by yalmog99** [comment]
@ofirmanor thanks, working great !
