### ISSUE TITLE
Missing precipitation_probability attribute

### ISSUE THREAD

**Issue by maorcc** [GuyKh/ims-custom-component#127]
I do not see any rain prediction information with this integration. Does IMS provide no such data?

Here is a comparison to OpenWeatherMap using the `custom:weather-chart-card` showing that OpenWeatherMap contains rain prediction while the IMS integration does not:

![image](https://github.com/user-attachments/assets/19c4d8fa-2f50-4ed8-9db1-686b181bd7ee)

**Comment by GuyKh** [comment]
I believe this is already implemented.
If you use the action for `Get Weather` - `Hourly`.
You'd see something of this sort:
```
    - condition: pouring
      datetime: "2024-12-29T20:00:00+02:00"
      precipitation_probability: 45
      wind_bearing: 180
      uv_index: 0
      temperature: 14.9
      wind_speed: 3
      precipitation: 12.43
      humidity: 73
```

As you can see - it's already reported

**Comment by GuyKh** [comment]
** Hourly ** data show correct.
![image](https://github.com/user-attachments/assets/fe9631b2-593b-40ce-af06-319382298a37)

I think what you're describing is the Daily data.

**Comment by GuyKh** [comment]
For **DAILY** - 
This is the data received on the daily resolution from IMS:
```
        "daily": {
          "id": "111495352",
          "lid": "2",
          "forecast_date": "2024-12-30",
          "weather_code": "1020",
          "minimum_temperature": "10",
          "maximum_temperature": "15",
          "maximum_uvi": "2",
          "created": "2024-12-28 05:11:06",
          "u_v_i_factor": "0.5"
        },
```

As you can see, I'm getting the following fields:
- Condition (`weather_code`)
- Min/Max temperature
- Max UVI
- UVI factor

but no information about rain or wind.
You can add a custom template sensor to calculate it, but I don't plan to add these as these are just representation of the data from IMS

**Comment by GuyKh** [comment]
Closing as won't fix
