### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by Gugulator** [GuyKh/ims-custom-component#20]
Hi.
inside main weather entity if there are 2 attributes:
visibility_unit: km
precipitation_unit: mm

but there are data itself for those parameters are missing. 
I mean that visibility and precipitation are not exist.
is it possible to fix?

**Comment by GuyKh** [comment]
The data is pulled from IMS website -- 
For example: https://ims.gov.il/en/full_forecast_data/2
As you can see, not all available fields can be filled, but in #21 I've enhanced the hourly weather forecast.
When version `0.1.4` will be released, please let me know if that suits you

**Comment by Gugulator** [comment]
is it possible also remove unnecessary word "value" from attributes?
for example, today forecast sensor looks like this:
````
minimum_temperature: 
value: '14'
unit: °C

maximum_temperature: 
value: '22'
unit: °C

uvi: 
value: '6'
unit: uv

weather : 
value: Partly cloudy
icon: mdi:weather-partly-cloudy

description: 
value: ' Partly cloudy to clear. It will remain unseasonably warm.'

date: 
value: 2023/03/12
````

but it will be more useful and readable for humans and also other integrations and interface if it will looks like this:
````
minimum_temperature: '14'
unit: °C

maximum_temperature: '22'
unit: °C

uvi: '6'
unit: uv

weather : Partly cloudy
icon: mdi:weather-partly-cloudy

description: ' Partly cloudy to clear. It will remain unseasonably warm.'

date: 2023/03/12
````
and so on...

**Comment by Gugulator** [comment]
by the way, if you are going to developer tools and open template editor and try to get value of attribute, for example in this way:
```
{{ (state_attr('sensor.ims_forecast_today', 'description') | string) }}
```

it will get output like this:
```
{
  "value": " Partly cloudy to clear. It will remain unseasonably warm."
}
```

**Comment by GuyKh** [comment]
@Gugulator - please check with 0.1.4

**Comment by Gugulator** [comment]
> @Gugulator - please check with 0.1.4

i don't see the difference.
visibility_unit and precipitation_unit still present, without visibility and precipitation attributes.
maybe it is will be better exclude those parameters if you don't have measurement data for this?



also still displays word VALUE for each forecast sensor attribute.

for example:
global sensor - weather.ims
have attributes:
```
temperature: 16
temperature_unit: °C
humidity: 53
pressure_unit: hPa
wind_bearing: 315
wind_speed: 4
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
```

other forecast sensors have attributes with word VALUE.
for example sensor.ims_forecast_today:
```
minimum_temperature: 
value: 14
unit: °C

maximum_temperature: 
value: 23
unit: °C

uvi: 
value: 6
unit: uv

weather : 
value: Partly cloudy
icon: mdi:weather-partly-cloudy

description: 
value: >-
  This evening and tonight: Clear to partly cloudy. Chance of mist in the
  southern coastal plain and the northern Negev.

date: 
value: 2023/03/12
```

**Comment by GuyKh** [comment]
As for the Weather sensor, as you can read here - [in the HomeAssistant developer documentation](https://developers.home-assistant.io/docs/core/entity/weather/) - you **can** (not required) to set values for various fields - e.g. `native_visibility` and `native_visibility_unit` - if None is set, units fallback to it's default value (I think it's a global configuration for HomeAssistant - metric/imperial units etc).

Anyway, I've added logic for the perpitation (rain mm) in `0.1.4` but visibility is a data which HA **can present** but IMS doesn't provide - so there's nothing I can help with

As for the Sensor properties - I'll try to look
