### ISSUE TITLE
"Exceptional" forecast?

### ISSUE THREAD

**Issue by quartzbear** [GuyKh/ims-custom-component#29]
Hi Tomer

I've been using your addon for a couple weeks. Today I got this:
![image](https://user-images.githubusercontent.com/33700415/230761628-6247248b-7ac4-4829-a044-0e2db97272cb.png)
Is it trying to say Sharav (שרב)?

Thanks

**Comment by quartzbear** [comment]
Everything seems to be working otherwise:
![image](https://user-images.githubusercontent.com/33700415/230761703-ce99b855-f9b4-4d2f-86c1-3c881873d896.png)

**Comment by GuyKh** [comment]
@quartzbear
look. 
The weather in IMS is coded by this list:
https://ims.gov.il/en/weather_codes

HomeAssistant native weather condition is listed here:
https://developers.home-assistant.io/docs/core/entity/weather/#recommended-values-for-state-and-condition

The mapping is here:
https://github.com/t0mer/ims-custom-component/blob/main/custom_components/ims/const.py#L114

Status 1580 ("Extremely Hot") in IMS is mapped to "Exceptional".
Do you have another mapping suggestion?

**Comment by quartzbear** [comment]
Given the available conditions from HA, I guess "Exceptional" is the most suitable. Maybe changing the default graphic would make it more clear?
I guess most HA devs are based in cold countries, so the idea of adding statuses for hot weather didn't occur to them.

**Comment by GuyKh** [comment]
It's automatic in HomeAssistant. I can just control the predifined condition name

**Comment by GuyKh** [comment]
Closing this ticket. @quartzbear - Let me know if you have other thoughts?

**Comment by quartzbear** [comment]
No, nothing to add. Thanks
