### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by bikingbadger** [GuyKh/ims-custom-component#58]
Trying to add the integration after downloading from HACS.
I find it in the integrations but after `Please wait, starting configuration wizard for The Israel Meteorological Service integration` which takes a long time I get `Config flow could not be loaded: Unknown error`
Not sure where to get logs from but if you could help debug this I would appreciate it

**Comment by ytzlax** [comment]
I also experience the same with HA version  2023.9

**Comment by GuyKh** [comment]
I just tried it with an empty HA installation and it works ok.

Could you paste the log from the failure?

**Comment by bikingbadger** [comment]
Hi @GuyKh ,

I understand this is something probably on my side. I can't find any log related to this.

This is what happens when I add the integration and it runs for a really long time:
![image](https://github.com/t0mer/ims-custom-component/assets/4545860/0beecb1a-b74e-4cc2-86e5-1f279b26e8f5)

And then this is shown:
![image](https://github.com/t0mer/ims-custom-component/assets/4545860/95aa60bd-361d-4cae-a0cc-4ec217ea708d)

**Comment by GuyKh** [comment]
@bikingbadger  Can you see if theres any log printouts?

**Comment by bikingbadger** [comment]
I can't see anything in the logs, I have looked in Settings > System > Logs

Is there another place I should look at?

**Comment by GuyKh** [comment]
@bikingbadger - in `home-assistant.log`

**Comment by bikingbadger** [comment]
@GuyKh thanks for the help. today i went to add the integration to see what the logs would do and it actually worked!! no idea what was different. thank you very much for the intergration.
