### ISSUE TITLE
Deprecated config in Home Assistant 2023.9.0

### ISSUE THREAD

**Issue by Gugulator** [GuyKh/ims-custom-component#59]
https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

The ims integration is using deprecated forecast
This stops working in version 2024.3.0. Please address before upgrading.
The integration ims is using the deprecated forecast attribute.

Please report it to the custom integration author..

**Comment by GuyKh** [comment]
#57 Already done.
I'm waiting a little bit for users of older versions to upgrade.
This would still work, until 2024.3

**Comment by mulikg** [comment]
How do I upgrade to the new version?

**Comment by GuyKh** [comment]
Merged and created a release.
This should be backward compatible for now
