### ISSUE TITLE
Wrong forecast values

### ISSUE THREAD

**Issue by KotBayun69** [GuyKh/ims-custom-component#60]
I believe the new get_forecast service reports forecast shifted to one day to the past in Your integration. I mean the first day in the forecast should be today, but actually it is for yesterday.

I accidentally noticed it when called the service from developers tools in Home Assistant. 
Returned forecast has first entry dated day before at T21:00:00+00:00 , but probably should be at midnight on the current day. It make sense because Israeli local time is UTC+3.

My guess you are using local time when calling the service, but the service is using UTC

**Comment by KotBayun69** [comment]
I am not a programmer, but I suspect Python is case sensitive language, but in your code line

`datetime = daily_forecast.date.astimezone(pytz.UTC).isoformat() `

UTC is in uppercase, but every code I see online use lowercase. Can it be the issue?

**Comment by KotBayun69** [comment]
Called the service for hourly forecast and get also forecast for two past hours. E.g current time is 18:15 so first forecast should be for 18:00 but got for 16:00 and 17:00

**Comment by GuyKh** [comment]
So, not exactly. The results value of get_forecast is just what the api returns (e.g. https://ims.gov.il/he/full_forecast_data/2)

You may have some point that I should filter only the current/future values

**Comment by KotBayun69** [comment]
> You may have some point that I should filter only the current/future values

So, the actual problem is at API  side. Not a surprise we usually get rain forecast for sunny day :)

**Comment by chepa92** [comment]
Now via API I've got rain only, and I see rain only in 2 days... API probably not broken

**Comment by GuyKh** [comment]
@chepa92 - can you elaborate?
Is there anything in the logs?

This is what I see:
![image](https://github.com/t0mer/ims-custom-component/assets/3136012/256e0c06-644f-486f-8fbc-5e8656b69453)
![image](https://github.com/t0mer/ims-custom-component/assets/3136012/e5aa061e-ecdb-4d88-8a2f-f058d5f3d10b)

I saw:
```
2024-01-29 12:54:41.152 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ims platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ims/sensor.py", line 283, in async_setup_entry
    for condition in conditions:
TypeError: 'NoneType' object is not iterable
```

**Comment by chepa92** [comment]
I found a problem, if I select English language, I've got data back 2 days and HA thinks today is -2 days, if select Hebrew everything good.

**Comment by chepa92** [comment]
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/32b884c3-96b0-4dae-8ae0-ee8b742cff63)
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/ca0159da-5a8e-4e32-9b96-168d44d49192)
as weather I don't see rain and if I use sensors I see rain.. so problem yes exists

**Comment by GuyKh** [comment]
@chepa92 - I think you can write in Hebrew since I can't understand the problem?

**Comment by chepa92** [comment]
1. as "weather.ims_weather" - no rain
2. as "sensor.ims_forecast_today" - there is rain

**Comment by GuyKh** [comment]
@chepa92 - I think I found what you're describing:
Data from IMS comes in weather codes - 
This is the [weather_code table](https://ims.gov.il/he/weather_codes) (code to description)

Here is the translation from code to:
1. [State](https://github.com/t0mer/ims-custom-component/blob/main/custom_components/ims/const.py#L145) (used in Weather entity)
2. [Weather Icon](https://github.com/t0mer/ims-custom-component/blob/main/custom_components/ims/const.py#L173) (used in Sensor)

Note that there's some discrepency, e.g. code `1530` is `ATTR_CONDITION_PARTLYCLOUDY` (HomeAssistant "Partly Cloudy") but also is with icon `mdi:weather-partly-rainy`.

This is the mix-up, I think - as there's an inherent mismatch between Home Assistant conditions (list [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/__init__.py#L96)) and MDI ([here](https://pictogrammers.com/library/mdi/))

If you want to suggest some different mappings, please do.

For reference -- what @chepa92 described can be seen here:
``` 
(Template:)
Weather: {{ states("weather.ims") }}
Sensor: {{ state_attr('sensor.ims_forecast_today', '16:00').weather.value }}

Results in:
Weather: partlycloudy
Sensor: Cloudy, possible rain
```

**More over - the code to description is coming from [here](https://github.com/t0mer/py-weatheril/blob/main/weatheril/utils.py#L2763)**

**Comment by chepa92** [comment]
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/d4420934-5455-45cb-a527-161b1686c6d8)
@GuyKh yeap, this is probably a problem, on their site they have 2 icons with 1 drop and 3 drops (weather-rainy, weather-partly-rainy) so yes probably mismatch, I think weather code 1540, 1530 should be a rain with 1 drop

**Comment by GuyKh** [comment]
@chepa92 the issue is with MDI icons, I can't find any "3 drop" one which suits

**Comment by chepa92** [comment]
@GuyKh I think statuses 1540 and 1530 should be weather-partly-rainy icon (official IMS icons have 3 drops not MDI icons, 1 drop is for statuses 1540 and 1530)

**Comment by GuyKh** [comment]
As you can see [here](https://github.com/t0mer/ims-custom-component/blob/main/custom_components/ims/const.py#L173) - this is already the case.

**Comment by chepa92** [comment]
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/ef01cede-0c8f-40a1-8544-bc9b53c63d87)
but why day is sunny, and hourly is rain?

**Comment by GuyKh** [comment]
Let's make sure you understand how this works.
The py package / component calls IMS every period of time to a single endpoing:
https://ims.gov.il/he/city_portal/2 - (`language: he` and `city: 2` = Tel Aviv).

There it gets 3 types of data.
Under `analysis` field - is the current weather = no forecast.
under `forecast_data` - you get two types of forecasts:
- `daily`
- `hourly`
This is self explainatory really, but in your picture you compare the `hourly` data (need to mention that not all hours are with `weather_code` status and if it's missing and it's the first hour, the "current" weather code from `analysis` would be used) and the `analysis/current` fields - which may be different.

**Comment by chepa92** [comment]
@GuyKh so `Weather: {{ states("weather.ims_weather") }}` should give me real time data? And not today forecast?

**Comment by GuyKh** [comment]
It should give the analysis value, not forecast

**Comment by chepa92** [comment]
And `analysis:"weather_code":null`.... I just thinking that weather.ims_weather should return weather right now or forecast for today otherwise data is not relevant to show on any dashboard

**Comment by GuyKh** [comment]
@chepa92 
[This](https://github.com/t0mer/ims-custom-component/blob/main/custom_components/ims/weather.py#L229) - is how the WeatherEntity condition is being calculated - some fallback flow there too

**Comment by chepa92** [comment]
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/a7509d7c-9ee5-4c01-bdae-86c7dd640361)
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/97f3b1e7-443e-4ebb-8032-fbcde333c40f)
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/9d53f139-62b2-48ff-91ba-f0607c101112)
@GuyKh Everything says it's rainy today, but WeatherEntity still telling it's cloudy, sorry, I don't know how debug this component

**Comment by GuyKh** [comment]
Checked again with city = 7 (Netanya):
Everything says "Rainy"
![Uploading image.png…]()

**Comment by chepa92** [comment]
![image](https://github.com/t0mer/ims-custom-component/assets/31892489/61955c79-5763-44fd-a41c-4c041bf45fc8)
Both of my HA instances don't see any rain :(

**Comment by GuyKh** [comment]
@chepa92 - are you talking about city 7 (Netanya)?

**Comment by chepa92** [comment]
@GuyKh yes

**Comment by GuyKh** [comment]
@chepa92 - The only thing I can think of is that this is a sync issue - 
Can you try to:
A) Restart HomeAssistant and see if this changes?
B) Remove the integration, restart and re-add it again and see if this changes?

**Comment by eyarz** [comment]
@GuyKh same issue here after I tried to restart HA and re-install integration.
according to HA forecast it is `partlycloudy` all week when it should also be raining (city code: 20)...

**HA**
![image](https://github.com/t0mer/ims-custom-component/assets/19731161/75d40db6-992a-4454-9418-f0024e53d606)

**IMS**
![image](https://github.com/t0mer/ims-custom-component/assets/19731161/3f6c86ca-b359-45c6-bc4f-96decccc848e)

**Comment by GuyKh** [comment]
Ok, so, once again - @eyarz and @chepa92 
Please don't compare the icons in IMS site and the icons in the integration, that's two systems which implement "weather_code - to - icon" individually.

I'm looking at city = 20 = Ramla.
Looking at the data that IMS exposes:  https://ims.gov.il/en/city_portal/20
```
https://ims.gov.il/en/city_portal/20
                   ^^^           ^^^
                Language    CityCode
```

I'm getting in Json:
```
// Current Weather
data.analysis.weather_code = 1540

// Hourly Forecast
data.forecast_data.hourly."11:00".weather_code = 1540
```

Looking at the mapping I mentioned above - `1540` is translated to: `mdi:weather-partly-rainy` ([see here](https://github.com/t0mer/ims-custom-component/blob/main/custom_components/ims/const.py#L187C1-L187C40))

In the sensor description (`sensor.ims_today`) - I'm seeing:
```
11:00: 
weather:
  value: Cloudy, possible rain
  icon: mdi:weather-partly-rainy
temperature:
  value: 15.3
  unit: °C
```

About WeatherSensor.
You can see [here](https://github.com/t0mer/ims-custom-component/blob/main/custom_components/ims/const.py#L165C13-L165C40) - that `1540` is translated to HomeAssistant condition `ATTR_CONDITION_PARTLYCLOUDY` - [This is all](https://github.com/home-assistant/core/blob/f6d2f6117a0a4067fd3ff707a34c7dea0a63c84b/homeassistant/components/weather/__init__.py#L104) the variants in HomeAssistant conditions.

Looking at the IMS [weather_code description](https://ims.gov.il/en/weather_codes) - when checking `1540`:
```
{
"id": "14",
"desc_en": "Cloudy, possible rain",
"weather_code": "1540",
"ims_order": "14",
"night": "0",
"display": "1",
"desc": "Cloudy, possible rain"
},
```
So "**Cloudy, possible rain**" - could be translated to a different condition - but that's a whole different discussion than the saying "Wrong Data" - you're putting on here.
Also - as you can see in the SensorDescription "Cloudy, Possible Rain" is there

**Comment by eyarz** [comment]
thank you for the detailed answer!
so basically I should ignore the icons at `weather.ims_weather` because they are not translated correctly.
Is there a recommended way to create a card that can show me a weather forecast correctly?

**Comment by GuyKh** [comment]
@eyarz I actually suggest you to do the opposite and suggest a fix, i.e. What mapping should we correct?

**Comment by GuyKh** [comment]
@eyarz @chepa92 - I've done some changes in the icon mapping.
Can you update to 0.1.24 and give it a try?

**Comment by eyarz** [comment]
Wow, that was a quick fix!
I updated to version 0.1.24 and the icons looks the same as the IMS forecast 🤩

**Comment by KotBayun69** [comment]
Sorry to wake this up, but I think I found the source of my original problem.
As IMS website in API section states:

> The observation date is always in Israel winter time (UTC + 2), and not as mentioned in the output datetime +03:00

When I opened the issue, we were on summer time, that’s why there were time differences.

**Comment by GuyKh** [comment]
> Sorry to wake this up, but I think I found the source of my original problem. As IMS website in API section states:
> 
> > The observation date is always in Israel winter time (UTC + 2), and not as mentioned in the output datetime +03:00
> 
> When I opened the issue, we were on summer time, that’s why there were time differences.

I think that is said in the context of IMSEnvista API and not the forecast API. As data is written in a 3 hour window (0,3,6,9...) and the data is fetched hourly...
