### ISSUE TITLE
Deprecated Values for IMS 0.1.20 HA OS 2024.1.3 11.4

### ISSUE THREAD

**Issue by Gugulator** [GuyKh/ims-custom-component#72]
IMS version: 0.1.20
Home Assistant OS
Core: 2024.1.3
Supervisor: 2023.12.0
Operating System: 11.4
Frontend: 20240104.0

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 12:40:33 (3 occurrences)
Last logged: 12:40:33

LENGTH_MILLIMETERS was used from ims, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILLIMETERS instead, please create a bug report at https://github.com/t0mer/ims-custom-component/issues

PRESSURE_HPA was used from ims, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please create a bug report at https://github.com/t0mer/ims-custom-component/issues

SPEED_METERS_PER_SECOND was used from ims, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead, please create a bug report at https://github.com/t0mer/ims-custom-component/issues

**Comment by GuyKh** [comment]
Fixed. Would be available on next version, for now it's just a log warning
