### ISSUE TITLE
Integration fails to load. IMS 0.1.22

### ISSUE THREAD

**Issue by Gugulator** [GuyKh/ims-custom-component#83]
Error #1:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 20:38:59 (1 occurrences)
Last logged: 20:38:59

Error while setting up ims platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ims/sensor.py", line 283, in async_setup_entry
    for condition in conditions:
TypeError: 'NoneType' object is not iterable

Error #2:

This error originated from a custom integration.
Logger: custom_components.ims
Source: custom_components/ims/__init__.py:157
Integration: The Israel Meteorological Service integration ([documentation](https://github.com/t0mer/ims-custom-component), [issues](https://github.com/t0mer/ims-custom-component/issues))
First occurred: 20:38:59 (1 occurrences)
Last logged: 20:38:59

Key monitored_conditions is missing from config_entry.data

-----
HA OS
Core 2024.1.3
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

IMS 0.1.22

**Comment by mulikg** [comment]
I also have the same problem

**Comment by GuyKh** [comment]
I'll try to fix it quickly, but as a quick workaround, remove the component and re-add it (no need for installation)

**Comment by Gugulator** [comment]
If it helps to investigate the issue, I missed update 0.1.21, so I jumped from version 0.1.20 to 0.1.22.

**Comment by vadimnazaroff** [comment]
Other ption is downgrade to 0.1.21 working version

**Comment by vadimnazaroff** [comment]
Hi, 
Was the problem resolved in 0.1.23?

**Comment by GuyKh** [comment]
@vadimnazaroff I believe so
