### ISSUE TITLE
IMS 0.1.23 Warning in logs: monitored_conditions is missing from config_entry.data

### ISSUE THREAD

**Issue by Gugulator** [GuyKh/ims-custom-component#85]
Logger: custom_components.ims
Source: custom_components/ims/__init__.py:159
Integration: The Israel Meteorological Service integration ([documentation](https://github.com/t0mer/ims-custom-component), [issues](https://github.com/t0mer/ims-custom-component/issues))
First occurred: 00:47:19 (1 occurrences)
Last logged: 00:47:19

Key monitored_conditions is missing from config_entry.data

---
HA OS
Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Comment by GuyKh** [comment]
@Gugulator - is this an upgrade or a clean installation?
If an upgrade -- this is a **warning**, not an **error** - which is as planned.

**Comment by GuyKh** [comment]
**For whoever reads this** - when moving to **selective** sensors (choose which sensors you want to create) - `monitored_conditions` is the list of which sensors to create.
When upgrading from an older version - the list **doesn't exist**.
This is just a **warning**, and it'll be gone when you reinstall the component (and so create the list)

**Comment by Gugulator** [comment]
issue resolved after full uninstall and clean install
