### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by shairevivo** [GuyKh/ims-custom-component#9]
Hi, seems like the api can return the amount of rain.
Can you add a threshold? 
I see raining status for 0.01mm which is not really raining.

2 options:
1. embed it in your code and "filter" any rain status below 0.1mm
2. let the user decide what is the amount of rain considered raining (~1mm for me)

**Comment by GuyKh** [comment]
I suggest maybe that you'll create a template (binary) sensor based on rain sensor, with your custom preferences.
Closing the issue for now.
