### ISSUE TITLE
Never show night icons

### ISSUE THREAD

**Issue by alondin** [GuyKh/ims-custom-component#91]
hey, great integration. but - I see only day icons, I can see that attributes for night are missing, shown only for day.
possible to add also night?

**Comment by GuyKh** [comment]
It relates to the fact that the reports from IMS don't have this granularity

**Comment by GuyKh** [comment]
Also - as you can read [here](https://developers.home-assistant.io/docs/core/entity/weather/#recommended-values-for-state-and-condition) the only night relevant icon is `clear-night` 
I can try to add it but I think it's a hard work

**Comment by alondin** [comment]
that can be great! Thank you.
From what i saw - night rainy or night sunny also can be shown.
