### ISSUE TITLE
uv sensor is always 0 + It failed a lot

### ISSUE THREAD

**Issue by tzagim** [GuyKh/ims-custom-component#93]
Both uv sensors show 0 all the time.

That way:
states.sensor.ims_forecast_today.attributes.maximum_uvi.value

I do get information.

In addition, many times it fails to receive information from ims, I receive the following message:
```[custom_components.ims.weather_update_coordinator] Error fetching ims data: 'NoneType' object has no attribute 'forecast_time'```

**Comment by GuyKh** [comment]
Can you add logs in `debug` for the second error (incl. few lines before and after)?

**Comment by GuyKh** [comment]
I know it's a bad answer, but from my installation (running the latest version) everything seems to be working fine:
![image](https://github.com/user-attachments/assets/58bdf376-d551-455b-a2ea-9bfc18103d1d)


You can try couple of things:
1. Check for updates
2. Reinstall the addon
3. Reconfigure the integration
4. Check with a different city
5. Check this link (change city from `2` (Tel Aviv) to the ones you select) [https://ims.gov.il/he/city_portal/2](https://ims.gov.il/he/city_portal/2) and see if you have values under `fixed_forecast_data` in fields like `u_v_index` etc.
6. If all looks OK. Send here your logs

**Comment by tzagim** [comment]
Hi, shortly after I posted the issue, I reinstalled the add-on and reconfigured it, and it only worked after restarting the system. Right now it's working fine, if it start crashing again I'll report.

I'm closing the issue for now.

Thank you!

**Comment by GuyKh** [comment]
There's one (minor) issue though - both `Current` and `Max` UV Level have the same label name.
This will be fixed soon
